### ISSUE TITLE
the play runner doesn't work with Play 2.6

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/sbt-aspectj-runner#11]
As mentioned in gitter by @ilya-nurullin.. let's take a look!

**Comment by JeroenMinnaert** [comment]
+1

**Comment by jaroslawZawila** [comment]
Is there any progress on this ??

**Comment by ivantopo** [comment]
Properly fixed with [v1.1.0](https://github.com/kamon-io/sbt-aspectj-runner/releases/tag/v1.1.0)
