### ISSUE TITLE
Publish for scala 2.12

### ISSUE THREAD

**Issue by valdo404** [kamon-io/sbt-aspectj-runner#13]
Hi guys, would it be possible to publish this to scala 2.12 and sbt 1 ?

Best regards

**Comment by pjfanning** [comment]
1 option is to use sbt-javaagent instead of sbt-aspectj-runner.
This commit demonstrates how to make the change - https://github.com/pjfanning/prometheus-akka-sample/commit/5d29db0289f106663092166cf45bdee4a3fe1711

**Comment by ivantopo** [comment]
Published for SBT 1.0 since 1.0.4, now [v1.1.0](https://github.com/kamon-io/sbt-aspectj-runner/releases/tag/v1.1.0) has been just published as well!
