### ISSUE TITLE
Cannot download 1.1.1 artifacts

### ISSUE THREAD

**Issue by ashleymercer** [kamon-io/sbt-aspectj-runner#28]
Firstly - thanks for the speedy turnaround on #26 :)

I'm trying to use the new jars with this configuration:

```
addSbtPlugin("io.kamon"             % "sbt-aspectj-runner"          % "1.1.1")
addSbtPlugin("io.kamon"             % "sbt-aspectj-runner-play-2.6" % "1.1.1")
```

but am getting the following error:

```
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		io.kamon:sbt-aspectj-runner-play-2.6:1.1.1 (scalaVersion=2.12, sbtVersion=1.0)
```

Setting the version numbers back to `1.1.0` seems to work fine.

**Comment by akalinovskiy** [comment]
@ashleymercer try with scala version dependent import `%%` like:
```
resolvers += Resolver.bintrayIvyRepo("kamon-io", "sbt-plugins")
addSbtPlugin("io.kamon" %% "sbt-aspectj-runner-play-2.6" % "1.1.1")
```

**Comment by ashleymercer** [comment]
Hi @akalinovskiy - as it happens I ended up going a different route with this project, so won't now be able to test this.
