### ISSUE TITLE
Overriding configuration file

### ISSUE THREAD

**Issue by tferi** [kamon-io/sbt-aspectj-runner#3]
Hi!

The default Play `run` command allows overriding config locations like this:

```
run -Dconfig.file=conf/whatever.conf
```

Is there a way to tell `aspectj-runner` to do the same somehow?

Thanks!

**Comment by dpsoft** [comment]
Hi @tferi,

currently `aspectj-runner` support override config locations with resource:

```
run -Dconfig.resource=whatever.conf
```

But I think that could be a good improvement.

Cheers.

**Comment by dpsoft** [comment]
@tferi I just release a new version of `aspectj-runner`  that supports [overriding-configuration](https://github.com/kamon-io/sbt-aspectj-runner#overriding-configuration-file) , the version is `0.1.3`

Cheers,

**Comment by tferi** [comment]
Thanks!
