### ISSUE TITLE
which repo host addSbtPlugin("io.kamon" % "aspectj-play-24-runner" % "0.1.3") 

### ISSUE THREAD

**Issue by kknd22** [kamon-io/sbt-aspectj-runner#6]
I encountered the following when try to use the plugin - should I add another repo to resolve it? Thaks

`[error] (*:update) sbt.ResolveException: unresolved dependency: io.kamon#aspectj-play-24-runner;0.1.3: not found`  
and this is the content in `plugins.sbt`  
`resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/ivy-releases/"`  
Thanks
cl

**Comment by dpsoft** [comment]
@kknd22 `aspectj-play-24-runner` doesn't exist!!. if you want the plugin for play `2.4.x` and above you need use only`aspectj-play-runner`.

https://github.com/kamon-io/sbt-aspectj-runner#configure-1
